### ISSUE TITLE
Errors when opening app and modifying preferences

### ISSUE THREAD

**Issue by toothdog** [rekkyrosso/ampcast#14]
(I'm running 0.9.9 on a x86 macbook) When I first open the app, and occasionally while modifying certain preferences (e.g. frame color in custom theme settings) I will get an error or a series of errors of the following type:
Unhandled Error
TypeError: mainWindow.setTitleBarOverlay is not a function
    at IpcMainImpl.<anonymous> (/Applications/ampcast.app/Contents/Resources/app.asar/src/main.js:114:20)
    at IpcMainImpl.emit (node:events:519:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:84396)
    at WebContents.emit (node:events:519:28)

Unhandled Error
TypeError: mainWindow.setTitleBarOverlay is not a function
    at IpcMainImpl.<anonymous> (/Applications/ampcast.app/Contents/Resources/app.asar/src/main.js:117:20)
    at IpcMainImpl.emit (node:events:519:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:84396)
    at WebContents.emit (node:events:519:28)

Unhandled Error
TypeError: mainWindow.setTitleBarOverlay is not a function
    at IpcMainImpl.<anonymous> (/Applications/ampcast.app/Contents/Resources/app.asar/src/main.js:122:20)
    at IpcMainImpl.emit (node:events:519:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:84396)
    at WebContents.emit (node:events:519:28)

Nothing else appears to be broken due to this, but it does make for an annoyance during navigation.

**Comment by rekkyrosso** [comment]
I'll fix this in the next release. At least you won't get an error.

**Comment by rekkyrosso** [comment]
I just created a new release (version 0.9.10). Does the problem still exist?

**Comment by rekkyrosso** [comment]
I'm going to assume this is fixed and close.
